artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_path: artifacts/data_ingestion/data
  original_data_path: research/data/

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_validation/train/
  data_ingestion_path: artifacts/data_ingestion/data

data_transformation:
  root_dir: artifacts/data_transformation
  data_validation_path: artifacts/data_validation/train
  vectorstore_path: artifacts/data_transformation/store.json
  embedding_model_name: sentence-transformers/all-mpnet-base-v2

model_trainer:
  root_dir: artifacts/model_trainer
  vectorstore_path: artifacts/data_transformation/store.json
  model_name: google_genai:gemini-2.5-flash-lite

model_evaluation:
  root_dir: artifacts/model_evaluation
